export default [
  {"pageContent": "How much butter do I need for Choc-Chip Oatmeal Cookies?", "metadata": {"textFromDocument": "1 Cup of Butter", "lineNumber": 27}},
  {"pageContent": "How much packed light brown sugar is required for Choc-Chip Oatmeal Cookies?", "metadata": {"textFromDocument": "1 Cup of Packed light brown sugar", "lineNumber": 29}},
  {"pageContent": "What is the amount of white sugar needed for Choc-Chip Oatmeal Cookies?", "metadata": {"textFromDocument": "1/2 Cup of White Sugar", "lineNumber": 31}},
  {"pageContent": "How many eggs are used in Choc-Chip Oatmeal Cookies?", "metadata": {"textFromDocument": "2 Eggs", "lineNumber": 33}},
  {"pageContent": "How much vanilla extract is needed for Choc-Chip Oatmeal Cookies?", "metadata": {"textFromDocument": "2 Teaspoons of Vanilla Extract", "lineNumber": 35}},
  {"pageContent": "What quantity of all-purpose flour is required for Choc-Chip Oatmeal Cookies?", "metadata": {"textFromDocument": "1 1/4 Cups of All-purpose flour", "lineNumber": 37}},
  {"pageContent": "How much baking soda is required for Choc-Chip Oatmeal Cookies?", "metadata": {"textFromDocument": "1/2 Teaspoon of Baking Soda", "lineNumber": 39}},
  {"pageContent": "How much salt is needed for Choc-Chip Oatmeal Cookies?", "metadata": {"textFromDocument": "1 Teaspoon of Salt", "lineNumber": 41}},
  {"pageContent": "What is the quantity of quick-cooking oats for Choc-Chip Oatmeal Cookies?", "metadata": {"textFromDocument": "3 Cups of Quick-cooking oats", "lineNumber": 43}},
  {"pageContent": "How much chopped walnuts are needed for Choc-Chip Oatmeal Cookies?", "metadata": {"textFromDocument": "1 Cup of Chopped Walnuts", "lineNumber": 45}},
  {"pageContent": "What is the amount of semi-sweet chocolate chips required for Choc-Chip Oatmeal Cookies?", "metadata": {"textFromDocument": "1 Cup of Semi-sweet chocolate chips", "lineNumber": 47}},
  {"pageContent": "What is the oven temperature for Choc-Chip Oatmeal Cookies?", "metadata": {"textFromDocument": "325°F", "lineNumber": 50}},
  {"pageContent": "How long should Choc-Chip Oatmeal Cookies bake?", "metadata": {"textFromDocument": "12 minutes", "lineNumber": 70}},

  {"pageContent": "How much white sugar is needed for Choc-Chip Cookies?", "metadata": {"textFromDocument": "1 Cup of White Sugar", "lineNumber": 87}},
  {"pageContent": "What amount of brown sugar is required for Choc-Chip Cookies?", "metadata": {"textFromDocument": "1/2 Cup of Brown Sugar", "lineNumber": 89}},
  {"pageContent": "How much salt do I need for Choc-Chip Cookies?", "metadata": {"textFromDocument": "1/2 Teaspoon of Salt", "lineNumber": 91}},
  {"pageContent": "How many eggs are used in Choc-Chip Cookies?", "metadata": {"textFromDocument": "1 1/2 Cup of Eggs", "lineNumber": 93}},
  {"pageContent": "How much butter is required for Choc-Chip Cookies?", "metadata": {"textFromDocument": "1 Cup of Butter", "lineNumber": 95}},
  {"pageContent": "What quantity of flour is needed for Choc-Chip Cookies?", "metadata": {"textFromDocument": "2 1/4 Cup of Flour", "lineNumber": 97}},
  {"pageContent": "How much baking soda is needed for Choc-Chip Cookies?", "metadata": {"textFromDocument": "1 Teaspoon of Baking Soda", "lineNumber": 99}},
  {"pageContent": "What is the amount of vanilla extract required for Choc-Chip Cookies?", "metadata": {"textFromDocument": "1 Teaspoon of Vannila Extrace", "lineNumber": 101}},
  {"pageContent": "How much milk is used in Choc-Chip Cookies?", "metadata": {"textFromDocument": "2 Tablespoons of Milk", "lineNumber": 103}},
  {"pageContent": "What quantity of chocolate chips do I need for Choc-Chip Cookies?", "metadata": {"textFromDocument": "2 Cups of Chocolate Chips", "lineNumber": 105}},
  {"pageContent": "What is the oven temperature for Choc-Chip Cookies?", "metadata": {"textFromDocument": "350ºF/180ºC", "lineNumber": 108}},
  {"pageContent": "How long should Choc-Chip Cookies bake?", "metadata": {"textFromDocument": "8-10 minutes", "lineNumber": 121}},

  {"pageContent": "How much all-purpose flour is required for Chocolate Cherry Cookies?", "metadata": {"textFromDocument": "1 Cup of All purpose flour", "lineNumber": 149}},
  {"pageContent": "What amount of unsweetened cocoa is needed for Chocolate Cherry Cookies?", "metadata": {"textFromDocument": "1/3 Cup of Unseweetenede Cocoa", "lineNumber": 151}},
  {"pageContent": "How much baking powder is used in Chocolate Cherry Cookies?", "metadata": {"textFromDocument": "1/2 Teaspoon of Baking Powder", "lineNumber": 153}},
  {"pageContent": "What quantity of baking soda is required for Chocolate Cherry Cookies?", "metadata": {"textFromDocument": "1/4 Teaspoon of Baking Soda", "lineNumber": 155}},
  {"pageContent": "How much salt do I need for Chocolate Cherry Cookies?", "metadata": {"textFromDocument": "1/4 Teaspoon of Salt", "lineNumber": 157}},
  {"pageContent": "How much butter is needed for Chocolate Cherry Cookies?", "metadata": {"textFromDocument": "1/3 Cup of Softened Butter", "lineNumber": 159}},
  {"pageContent": "What is the amount of vanilla extract used in Chocolate Cherry Cookies?", "metadata": {"textFromDocument": "1 Teaspoon of Vanilla Extract", "lineNumber": 161}},
  {"pageContent": "How many eggs are required for Chocolate Cherry Cookies?", "metadata": {"textFromDocument": "1 Large Egg", "lineNumber": 163}},
  {"pageContent": "What quantity of dried tart cherries is used in Chocolate Cherry Cookies?", "metadata": {"textFromDocument": "2/3 Cup of Dried tart cherries", "lineNumber": 165}},
  {"pageContent": "How much semisweet chocolate chips do I need for Chocolate Cherry Cookies?", "metadata": {"textFromDocument": "3 Tablespoons of Semmisweet chocolate chips", "lineNumber": 167}},
  {"pageContent": "What amount of cooking spray is used for Chocolate Cherry Cookies?", "metadata": {"textFromDocument": "1 Cup of Cooking spray", "lineNumber": 169}},
  {"pageContent": "What is the oven temperature for Chocolate Cherry Cookies?", "metadata": {"textFromDocument": "350°F", "lineNumber": 172}},
  {"pageContent": "How long should Chocolate Cherry Cookies bake?", "metadata": {"textFromDocument": "12 minutes", "lineNumber": 181}},

  {"pageContent": "Quantity of quick-oats needed for the Oatmeal Cookies?", "metadata": {"textFromDocument": "3 Cups of Quick-cooking oats", "lineNumber": 35}},
  {"pageContent": "Which flavoring is mixed into the cookies?", "metadata": {"textFromDocument": "Vanilla Extract", "lineNumber": 31}},
  {"pageContent": "Total preparation time for Choc-Chip Cookies?", "metadata": {"textFromDocument": "35mins", "lineNumber": 62}},
  {"pageContent": "Which component contributes to the cookies' chewiness?", "metadata": {"textFromDocument": "Brown Sugar", "lineNumber": 66}},
  {"pageContent": "What kind of nuts are used in the Oatmeal Cookie?", "metadata": {"textFromDocument": "Chopped Walnuts", "lineNumber": 36}},
  {"pageContent": "Total eggs required for Choc-Chip Cookies?", "metadata": {"textFromDocument": "1 1/2 Cups of Eggs", "lineNumber": 68}},  // Note: Same clarification as earlier about possible error in the original quantity

]
